Comparetype: ConnectionStrings
SourceConnectionString:
  Name: SourceConntion
  ConnectionString: Data Source=localhost;Initial Catalog=work;Integrated Security=SSPI;
TargetConnectionString:
  Name: TargetConntion
  ConnectionString: Data Source=localhost;Initial Catalog=workdiff;Integrated Security=SSPI;

