Comparetype: ConnectionStrings
SourceConnectionString:
  Name: SourceConntion
  ConnectionString:  Data Source=localhost;Initial Catalog=Gateway;Integrated Security=SSPI;
TargetConnectionString:
  Name: TargetConntion
  ConnectionString: Data Source=localhost;Initial Catalog=Gateway;Integrated Security=SSPI;
Includes:
  - Schema: dbo
    ObjectType: SqlProcedure
    ObjectName: SelectCustomers
  - Schema: dbo
    ObjectType: SqlTable
    ObjectName: Testing


  
